"""Memory indexer — scans session logs, builds the tag map (tags.json + TAGS.md)."""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from app.memory.store import chats_dir, index_dir, init_root
from app.memory.tags import extract_tags

_HEADER_RE = re.compile(r"^## (.+)$", re.MULTILINE)
_TS_RE = re.compile(r"^_(.+?)_\s*$", re.MULTILINE)


def parse_exchanges(text: str) -> list[dict]:
    """Structured view of a session log — one dict per `## header` exchange."""
    out: list[dict] = []
    for header, body in _split_sections(text):
        tm = _TS_RE.search(body)
        um = re.search(r"\*\*user:\*\*\s*(.*?)(?=\n\*\*assistant:\*\*|\Z)", body, re.DOTALL)
        am = re.search(r"\*\*assistant:\*\*\s*(.*?)(?=\n`#|\Z)", body, re.DOTALL)
        out.append(
            {
                "header": header,
                "timestamp": tm.group(1).strip() if tm else "",
                "user": um.group(1).strip() if um else "",
                "assistant": am.group(1).strip() if am else "",
                "tags": extract_tags(body),
            }
        )
    return out


def _split_sections(text: str) -> list[tuple[str, str]]:
    """Return [(header_title, section_body)] for each `## header` in a session log."""
    out: list[tuple[str, str]] = []
    matches = list(_HEADER_RE.finditer(text))
    for i, m in enumerate(matches):
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        out.append((m.group(1).strip(), text[start:end]))
    return out


def _render_tags_md(counts: dict[str, int]) -> str:
    lines = ["# Tags", "", "_Generated by AIEA memory — do not edit; runs on reindex._", ""]
    for tag, n in sorted(counts.items()):
        lines.append(f"- `#{tag}` ({n})")
    return "\n".join(lines) + "\n"


def reindex(root: Path) -> dict:
    """Rebuild index/tags.json + index/TAGS.md from the session logs. Returns a summary."""
    init_root(root)
    tag_map: dict[str, list[dict]] = {}
    sessions = 0
    headers = 0

    for path in sorted(chats_dir(root).glob("*.md")):
        sessions += 1
        text = path.read_text(encoding="utf-8", errors="replace")
        for header, body in _split_sections(text):
            headers += 1
            for tag in extract_tags(body):
                tag_map.setdefault(tag, []).append({"session": path.stem, "header": header})

    counts = {t: len(v) for t, v in sorted(tag_map.items())}
    payload = {
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "sessions": sessions,
        "headers": headers,
        "counts": counts,
        "tags": tag_map,
    }
    (index_dir(root) / "tags.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (index_dir(root) / "TAGS.md").write_text(_render_tags_md(counts), encoding="utf-8")
    return {"sessions": sessions, "headers": headers, "tags": len(counts)}
