"""initial schema

Revision ID: 2fcd563bf3b0
Revises: 
Create Date: 2026-05-13 09:48:26.473236

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2fcd563bf3b0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_courses_code')
    )
    op.create_table('task_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('active_skills', sa.JSON(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_routes_task', 'task_routes', ['task'], unique=True)
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('instructions_md', sa.Text(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('vault_path', sa.String(length=1024), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=32), nullable=True),
    sa.Column('extraction_status', sa.String(length=16), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prompt_md', sa.Text(), nullable=False),
    sa.Column('answer_md', sa.Text(), nullable=False),
    sa.Column('distractors', sa.JSON(), nullable=False),
    sa.Column('worked_solution_md', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('bloom', sa.String(length=16), nullable=True),
    sa.Column('est_minutes', sa.Integer(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('source_material_ids', sa.JSON(), nullable=False),
    sa.Column('source_pages', sa.JSON(), nullable=False),
    sa.Column('evaluation_md', sa.Text(), nullable=True),
    sa.Column('eval_correctness', sa.Float(), nullable=True),
    sa.Column('eval_clarity', sa.Float(), nullable=True),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('vault_path', sa.String(length=1024), nullable=False),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_course_status', 'questions', ['course_id', 'status'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('current_provider', sa.String(length=32), nullable=False),
    sa.Column('current_model', sa.String(length=128), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'question_id', name='uq_examq')
    )
    op.create_table('provider_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('external_session_id', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_iterations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('iteration_no', sa.Integer(), nullable=False),
    sa.Column('focus', sa.String(length=32), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('vault_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qiter_question_seq', 'question_iterations', ['question_id', 'iteration_no'], unique=True)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider_session_id', sa.UUID(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.ForeignKeyConstraint(['provider_session_id'], ['provider_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_messages_conv_seq', 'ai_messages', ['conversation_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_messages_conv_seq', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index('ix_qiter_question_seq', table_name='question_iterations')
    op.drop_table('question_iterations')
    op.drop_table('provider_sessions')
    op.drop_table('exam_questions')
    op.drop_table('ai_conversations')
    op.drop_index('ix_questions_course_status', table_name='questions')
    op.drop_table('questions')
    op.drop_table('materials')
    op.drop_table('exams')
    op.drop_index('ix_task_routes_task', table_name='task_routes')
    op.drop_table('task_routes')
    op.drop_table('courses')
    # ### end Alembic commands ###
