"""extraction_versions table

Revision ID: 502d0b35047e
Revises: d1518a5d9075
Create Date: 2026-05-16 20:37:59.763531

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '502d0b35047e'
down_revision: str | None = 'd1518a5d9075'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('vault_path', sa.String(length=1024), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('eval_score', sa.Integer(), nullable=True),
    sa.Column('eval_notes', sa.Text(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'method', name='uq_extraction_versions_material_method')
    )
    op.create_index(op.f('ix_extraction_versions_material_id'), 'extraction_versions', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_versions_material_id'), table_name='extraction_versions')
    op.drop_table('extraction_versions')
    # ### end Alembic commands ###
