"""exam origin + tex/pdf paths

Revision ID: 6dcb4f2ce747
Revises: cc4b6347b388
Create Date: 2026-05-19 18:34:32.931169

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6dcb4f2ce747'
down_revision: str | None = 'cc4b6347b388'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_questions', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('exams', sa.Column('origin', sa.String(length=24), server_default='generated', nullable=False))
    op.add_column('exams', sa.Column('status', sa.String(length=16), server_default='draft', nullable=False))
    op.add_column('exams', sa.Column('tex_path', sa.String(length=1024), nullable=True))
    op.add_column('exams', sa.Column('pdf_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'pdf_path')
    op.drop_column('exams', 'tex_path')
    op.drop_column('exams', 'status')
    op.drop_column('exams', 'origin')
    op.drop_column('exam_questions', 'category')
    # ### end Alembic commands ###
