"""task_route context_length

Revision ID: 7324b361fe0d
Revises: 502d0b35047e
Create Date: 2026-05-17 10:14:13.742517

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7324b361fe0d'
down_revision: str | None = '502d0b35047e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_routes', sa.Column('context_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_routes', 'context_length')
    # ### end Alembic commands ###
