"""course paths and material collection

Revision ID: 73f07d7015b7
Revises: 2fcd563bf3b0
Create Date: 2026-05-13 16:20:29.222771

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '73f07d7015b7'
down_revision: str | None = '2fcd563bf3b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('language', sa.String(length=8), nullable=True))
    op.add_column('courses', sa.Column('materials_path', sa.String(length=1024), nullable=True))
    op.add_column('courses', sa.Column('brain_path', sa.String(length=1024), nullable=True))
    op.add_column('courses', sa.Column('library_path', sa.String(length=1024), nullable=True))
    op.add_column('courses', sa.Column('workshop_path', sa.String(length=1024), nullable=True))
    op.add_column('materials', sa.Column('collection', sa.String(length=32), nullable=False))
    op.add_column('materials', sa.Column('subpath', sa.String(length=1024), nullable=False))
    op.create_unique_constraint('uq_materials_course_subpath', 'materials', ['course_id', 'subpath'])
    op.drop_column('materials', 'vault_path')
    op.drop_column('materials', 'kind')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('kind', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('materials', sa.Column('vault_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_constraint('uq_materials_course_subpath', 'materials', type_='unique')
    op.drop_column('materials', 'subpath')
    op.drop_column('materials', 'collection')
    op.drop_column('courses', 'workshop_path')
    op.drop_column('courses', 'library_path')
    op.drop_column('courses', 'brain_path')
    op.drop_column('courses', 'materials_path')
    op.drop_column('courses', 'language')
    # ### end Alembic commands ###
