"""validation findings + exam validation status

Revision ID: 823e5aa9ec1e
Revises: e7f4c1d8a0b3
Create Date: 2026-08-12 15:14:24.008232

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '823e5aa9ec1e'
down_revision: str | None = 'e7f4c1d8a0b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('detail_md', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('auto_fixable', sa.Boolean(), nullable=False),
    sa.Column('fix_diff', sa.Text(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_findings_exam_status', 'validation_findings', ['exam_id', 'status'], unique=False)
    op.create_index('ix_validation_findings_question', 'validation_findings', ['question_id'], unique=False)
    op.add_column('exams', sa.Column('validation_status', sa.String(length=16), server_default='unvalidated', nullable=False))
    op.add_column('exams', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exams', sa.Column('validation_override_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'validation_override_reason')
    op.drop_column('exams', 'validated_at')
    op.drop_column('exams', 'validation_status')
    op.drop_index('ix_validation_findings_question', table_name='validation_findings')
    op.drop_index('ix_validation_findings_exam_status', table_name='validation_findings')
    op.drop_table('validation_findings')
    # ### end Alembic commands ###
