"""task route models

Revision ID: a5231d6508d5
Revises: b8f7bf38ff07
Create Date: 2026-05-15 23:25:58.087939

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a5231d6508d5'
down_revision: str | None = 'b8f7bf38ff07'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_route_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['task_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task_routes', sa.Column('context_mode', sa.String(length=16), nullable=False))
    op.add_column('task_routes', sa.Column('share_key', sa.String(length=64), nullable=True))
    op.drop_column('task_routes', 'model')
    op.drop_column('task_routes', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_routes', sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('task_routes', sa.Column('model', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('task_routes', 'share_key')
    op.drop_column('task_routes', 'context_mode')
    op.drop_table('task_route_models')
    # ### end Alembic commands ###
