"""question category + provenance

Revision ID: cc4b6347b388
Revises: 7324b361fe0d
Create Date: 2026-05-19 15:43:16.099277

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cc4b6347b388'
down_revision: str | None = '7324b361fe0d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('questions', sa.Column('origin', sa.String(length=24), server_default='ai-generated', nullable=False))
    op.add_column('questions', sa.Column('created_by', sa.String(length=80), nullable=True))
    op.add_column('questions', sa.Column('source_ref', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'source_ref')
    op.drop_column('questions', 'created_by')
    op.drop_column('questions', 'origin')
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###
