"""question chapter_id + elo_ids

Revision ID: d1518a5d9075
Revises: a5231d6508d5
Create Date: 2026-05-16 18:18:31.312284

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd1518a5d9075'
down_revision: str | None = 'a5231d6508d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('chapter_id', sa.String(length=32), nullable=True))
    op.add_column(
        'questions',
        sa.Column('elo_ids', sa.JSON(), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'elo_ids')
    op.drop_column('questions', 'chapter_id')
    # ### end Alembic commands ###
