"""question feedback_md column

Revision ID: ecf18336f678
Revises: 6dcb4f2ce747
Create Date: 2026-05-19 23:34:50.306641

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ecf18336f678'
down_revision: str | None = '6dcb4f2ce747'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('feedback_md', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'feedback_md')
    # ### end Alembic commands ###
